gestion_stock_homepage:
    path:     /produit
    defaults: { _controller: GestionStockBundle:Default:index }

gestion_stock_ajouter_produit:
    path:     /produit/ajouter
    defaults: { _controller: GestionStockBundle:Produit:ajouter }

gestion_stock_afficher_produit:
    path:     /produit/afficher/{code}
    defaults: { _controller: GestionStockBundle:Produit:afficher }

gestion_stock_lister_produit:
    path:     /produit/lister
    defaults: { _controller: GestionStockBundle:Produit:lister }

gestion_stock_modifier_produit:
    path:     /produit/modifier/{codebarre}
    defaults: { _controller: GestionStockBundle:Produit:modifier }

gestion_stock_supprimer_produit:
    path:     /produit/supprimer/{codebarre}
    defaults: { _controller: GestionStockBundle:Produit:supprimer }
    
gestion_stockage_lister_stock:
    path:     /stock/lister
    defaults: { _controller: GestionStockBundle:Stock:lister }

gestion_stockage_afficher_stock:
    path:     /stock/afficher/{Identifiant}
    defaults: { _controller: GestionStockBundle:Stock:afficher }

gestion_stockage_ajouter_stock:
    path:     /stock/ajouter
    defaults: { _controller: GestionStockBundle:Stock:ajouter }

gestion_stockage_modifier_stock:
    path:     /stock/modifier
    defaults: { _controller: GestionStockBundle:Stock:modifier }

gestion_stockage_supprimer_stock:
    path:     /stock/supprimer
    defaults: { _controller: GestionStockBundle:Stock:suprimer }


gestion_stock_categorie_ajouter:
    path:       /categorie/ajouter
    defaults:   {_controller: GestionStockBundle:Categorie:ajouter}

gestion_stock_categorie_lister:
    path:       /categorie/lister
    defaults:   {_controller: GestionStockBundle:Categorie:lister}

gestion_stock_categorie_modifier:
    path:       /categorie/modifer/{id}
    defaults:   {_controller: GestionStockBundle:Categorie:modifier}

gestion_stock_categorie_supprimer:
    path:       /categorie/supprimer/{id}
    defaults:   {_controller: GestionStockBundle:Categorie:supprimer}

gestion_stock_categorie_produit:
    path:       /categorie/produit/{id}
    defaults:   {_controller: GestionStockBundle:Categorie:produitCategorie}
