<?php

namespace Gestion\StockBundle\Repository;

/**
 * ChampdynamiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampdynamiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
